# Generated by Django 4.2.3 on 2023-08-11 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_advertisments", "0002_alter_advertisement_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="advertisement",
            table="advertisements",
        ),
    ]
